### PR TITLE
Fix iai-benchmarks workflow

### LINKED ISSUE #1230: Update the caches paths of the iai workflows
see https://github.com/lambdaclass/cairo-rs/pull/1215#issuecomment-1589417285

### PR DESCRIPTION
**Pull request by MegaRedHand**
## Description

Closes #1230

This PR updates the iai benchmarks workflow that wasn't working correctly after the `vm` crate was moved from the workspace root.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

### CODE REVIEW

File: bench/iai_benchmark.rs [hunk 1]
```diff
@@ -32,9 +32,17 @@ fn parse_program_helper() -> Program {
...
+        let program =
+            include_bytes!("../cairo_programs/benchmarks/keccak_integration_benchmark.json");
+        Program::from_bytes(program.as_slice(), Some("main")).unwrap()
+    };
+    let mut i = 10;
+    while i > 0 {
+        black_box(CairoRunner::new(black_box(&program), "starknet_with_keccak", false).unwrap());
+        i -= 1;
+    }
+    // core::mem::drop(black_box(runner));
```
Comment (Oppen) [inline bench/iai_benchmark.rs:45]: Why is the benchmark code changing here?

**Review by Oppen — APPROVED** [review]

File: bench/iai_benchmark.rs (hunk 1 above)
Comment (MegaRedHand) [reply bench/iai_benchmark.rs:45]: It's for testing the results on obvious performance regressions.

**Review by pefontana — APPROVED** [review]
Love it
